@NotificationGateway_HostAddress = https://localhost:7045


POST {{NotificationGateway_HostAddress}}/api/notificationgatewayservice/send
Content-Type: application/json

{
  "PhoneNumber":"1234567890",
  "AccountId":"123",
  "Message":"Hello"
}
###

GET {{NotificationGateway_HostAddress}}/api/notificationgatewayservice/business/1234567890

###

GET {{NotificationGateway_HostAddress}}/api/notificationgatewayservice/account/1234

###
